### ISSUE TITLE
global var / load as java class

### ISSUE THREAD

**Issue by zaoqi** [luaj/luaj#36]
```lua
...
local __TS__ArrayPush = function(arr, ...)
    local items = ({...});
    for ____TS_index = 1, #items do
        local item = items[____TS_index];
        arr[(#arr) + 1] = item;
    end
    return #arr;
end;
...
```

testtemp.java
```java
import org.luaj.vm2.*;
import org.luaj.vm2.lib.jse.*;
import java.util.Vector;

public class testtemp {

  private static Globals globals;
  private static boolean print = false;
  private static String encoding = null;

  public static void main(String[] args) throws Exception {

    // process args
    boolean interactive = (args.length == 0);
    boolean versioninfo = false;
    boolean processing = true;
    boolean nodebug = false;
    boolean luajc = false;
    Vector libs = null;

    // new lua state
    globals = JsePlatform.standardGlobals();
    String libname = "lang$luaj";
    LuaValue slibname = LuaValue.valueOf(libname);
    // load as java class
    LuaValue v = (LuaValue)Class.forName(libname).newInstance();
    v.call(slibname, globals);
    System.out.println("load as java class");
  }
}
```

------------------------
If I remove `local `

```
Exception in thread "main" java.lang.NullPointerException
        at lang$luaj.onInvoke(lang$luaj.lua:28)
        at org.luaj.vm2.lib.VarArgFunction.invoke(Unknown Source)
        at org.luaj.vm2.lib.VarArgFunction.call(Unknown Source)
        at testtemp.main(testtemp.java:27)
```

**Comment by Enyby** [comment]
Understood nothing. You should at least quote the code "lang$luaj".

**Comment by zaoqi** [comment]
`lang$luaj`

```lua
...
local __TS__ArrayPush = function(arr, ...)
    local items = ({...});
    for ____TS_index = 1, #items do
        local item = items[____TS_index];
        arr[(#arr) + 1] = item;
    end
    return #arr;
end;
...
```

**Comment by noncom** [comment]
@zaoqi could you clarify a couple of questions? 

1. which exactly `local` do you remove so that you are getting this error?
2. how do you load `lang$luaj` and what filename does it have? (including the extension)

**Comment by zaoqi** [comment]
@noncom 
* `local` of `local __TS__ArrayPush ...`

```java
import org.luaj.vm2.*;
import org.luaj.vm2.lib.jse.*;
import java.util.Vector;

public class testtemp {

  private static Globals globals;
  private static boolean print = false;
  private static String encoding = null;

  public static void main(String[] args) throws Exception {

    // process args
    boolean interactive = (args.length == 0);
    boolean versioninfo = false;
    boolean processing = true;
    boolean nodebug = false;
    boolean luajc = false;
    Vector libs = null;

    // new lua state
    globals = JsePlatform.standardGlobals();
    String libname = "lang$luaj";
    LuaValue slibname = LuaValue.valueOf(libname);
    // load as java class
    LuaValue v = (LuaValue)Class.forName(libname).newInstance();
    v.call(slibname, globals);
    System.out.println("load as java class");
  }
}
```

`lang$luaj.class`
