### ISSUE TITLE
[BUG] java.lang.NullPointerException

### ISSUE THREAD

**Issue by zaoqi** [luaj/luaj#41]
```
java.lang.NullPointerException
	at org.luaj.vm2.luajc.ProtoInfo.isReadWriteUpvalue(Unknown Source)
	at org.luaj.vm2.luajc.JavaBuilder.closureInitUpvalueFromLocal(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.scanInstructions(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.<init>(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.<init>(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.<init>(Unknown Source)
	at org.luaj.vm2.luajc.LuaJC.compileProtoAndSubProtos(Unknown Source)
	at org.luaj.vm2.luajc.LuaJC.compileAll(Unknown Source)
	at luajc.processFile(Unknown Source)
	at luajc.<init>(Unknown Source)
	at luajc.main(Unknown Source)
```
https://gitlab.com/the-language/the-language/blob/e2bcaaa686c11ddb5ab2afbe64ebe55173dcc8cc/core/pure/lua/lang.lua

**Comment by zaoqi** [comment]
https://gitlab.com/the-language/the-language/blob/4f266229f70b2462fec939a2530b29b880686fb6/core/pure/lua/lang.lua
```
java.lang.NullPointerException
	at org.luaj.vm2.luajc.ProtoInfo.isReadWriteUpvalue(Unknown Source)
	at org.luaj.vm2.luajc.JavaBuilder.closureInitUpvalueFromLocal(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.scanInstructions(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.<init>(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.<init>(Unknown Source)
	at org.luaj.vm2.luajc.JavaGen.<init>(Unknown Source)
	at org.luaj.vm2.luajc.LuaJC.compileProtoAndSubProtos(Unknown Source)
	at org.luaj.vm2.luajc.LuaJC.compileAll(Unknown Source)
	at luajc.processFile(Unknown Source)
	at luajc.<init>(Unknown Source)
	at luajc.main(Unknown Source)
```

**Comment by zaoqi** [comment]
https://gitlab.com/the-language/the-language/blob/4f266229f70b2462fec939a2530b29b880686fb6/core/pure/lua/lang.lua#L2255

It was caused by this `if`

**Comment by zaoqi** [comment]
It was caused by https://gitlab.com/the-language/the-language/blob/4f266229f70b2462fec939a2530b29b880686fb6/core/pure/lua/lang.lua#L2262

**Comment by zaoqi-unsafe** [comment]
```
java.lang.NullPointerException
        at org.luaj.vm2.luajc.ProtoInfo.isReadWriteUpvalue(ProtoInfo.java:473)                          at org.luaj.vm2.luajc.JavaBuilder.closureInitUpvalueFromLocal(JavaBuilder.java:655)             at org.luaj.vm2.luajc.JavaGen.scanInstructions(JavaGen.java:404)                                at org.luaj.vm2.luajc.JavaGen.<init>(JavaGen.java:49)
        at org.luaj.vm2.luajc.JavaGen.<init>(JavaGen.java:61)
        at org.luaj.vm2.luajc.JavaGen.<init>(JavaGen.java:41)
        at org.luaj.vm2.luajc.LuaJC.compileProtoAndSubProtos(LuaJC.java:94)
        at org.luaj.vm2.luajc.LuaJC.compileAll(LuaJC.java:82)
        at luajc.processFile(luajc.java:227)
        at luajc.<init>(luajc.java:155)
        at luajc.main(luajc.java:74)
```
