### ISSUE TITLE
luajava.bindClass raise classNotFindException

### ISSUE THREAD

**Issue by Justice-love** [luaj/luaj#65]
* platform: android
* usage: luajava.bindClass  and then raise classNotFindException
```
Caused by: org.luaj.vm2.LuaError: @Pic.lua:14 vm error: java.lang.ClassNotFoundException: com.ai.ipu.push.test.mock.edgehandle.recgnition.ObjRecApi
        at org.luaj.vm2.lib.jse.LuajavaLib.invoke(Unknown Source)
        at org.luaj.vm2.lib.VarArgFunction.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at com.zzx.script.LuaScriptEngine.execute(LuaScriptEngine.java:38)
```

* what i think
luaj use `java.lang.ClassLoader#getSystemClassLoader` to load app class in `org.luaj.vm2.lib.jse.LuajavaLib#classForName`

* lua script
``` lua
local cksName = 'com.ai.ipu.push.test.mock.edgehandle.recgnition.ObjRecApi'

function preNanoEnv(params)
    local objRecApi = luajava.bindClass(cksName)
    local rootPath = params[0]
    return objRecApi:preNanoEnv(rootPath)
end
```

**Comment by BigZhou15717498850** [comment]
I also encountered this problem

**Comment by Mikhael-Danilov** [comment]
I believe luaj itself would do nothing with this issue (as it android platform specific issue), your code however can:

- Create your own class loader as in: https://github.com/NYRDS/remixed-dungeon/blob/d884050a6ada32daeb42283b4f06f20fa09a9dcd/RemixedDungeon/src/main/java/com/nyrds/android/lua/MultiDexLuajavaLib.java#L13
- Load it in your lua state as in: https://github.com/NYRDS/remixed-dungeon/blob/d556e6c0d5f07765f59e1da39e5af6facf6d9c9d/RemixedDungeon/src/main/java/com/nyrds/android/lua/LuaEngine.java#L114

**Comment by IoIxD** [comment]
Better late then never: This was valid at some point. But as of 2.0.1 (before you think of downgrading, that version is ten years old and isn't even close to the one this repo) you can only bind Java classes.

I suggest this change be reverted. I cannot think of a good reason for this.
